{{ if .Values.configurations.create }}
apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  name: {{ .Values.cluster.configurations.sgPostgresConfig }}
  {{- if and .Release.IsInstall .Values.cluster.create }}
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight": "-1"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  {{- end }}
spec:
  {{- if eq .Values.cluster.postgres.version "latest" }}
  postgresVersion: "13"
  {{- else }}
  postgresVersion: "{{ index (.Values.cluster.postgres.version | splitList ".") 0 }}"
  {{- end }}
  {{- with (index .Values.configurations.postgresconfig "postgresql.conf") }}
  postgresql.conf:
  {{- range $key, $value := . }}
    {{ $key }}: '{{ $value }}'
  {{- end }}
  {{- end }}
{{ end }}
